spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://217.60.249.94:3306/personal_cloud?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8
    username: personal
    password: 12345678
  mybatis:
    mapper-locations: classpath:mapper/*.xml
    type-aliases-package: com.example.yunclouddisktransfer.entity

thumbnail:
  sizeList:
    - 200
    - 400
    - 800
  videoFrameSecond: 5

aws:
  s3:
    endpoint: http://217.60.249.94:9000
    accessKey: minio
    secretKey: 12345678
    bucket: personal
    region: us-east-1
rocketmq:
  name-server: 217.60.249.94:9876
  consumer:
    group: transfer_file_group